### ISSUE TITLE
Search part of word

### ISSUE THREAD

**Issue by ghost** [pmatseykanets/laravel-scout-postgres#14]
Hello,
Is it possible to enable search for part of word?
For example search for "Postgre" and find "PostgreSQL".

Kind regards,
Salvis.

**Comment by countnoobula** [comment]
Tagging #10 for relevance

**Comment by xxRockOnxx** [comment]
trying to avoid forking and hardcoding the solution. Is there a temporary way I could do this while it is not yet implemented?

**Comment by pmatseykanets** [comment]
Please see #20
