### ISSUE TITLE
How to sort or order by the search results with specific columns?

### ISSUE THREAD

**Issue by tortuetorche** [pmatseykanets/laravel-scout-postgres#16]
Apparently [`laravel-scout-elastic`](https://github.com/ErickTamayo/laravel-scout-elastic/pull/48/files) package can do it, but I'm not sure if this postgres engine can do it without some refactoring...

**Comment by pmatseykanets** [comment]
Thanks for bringing my attention to this.

Just pushed a commit that should resolve it.

You can use `orderBy()` on a builder instance to define a custom order.
If  a custom order is not defined then the default one (`rank DESC, id ASC`) is used.
