### ISSUE TITLE
Scout 7 on Laravel 7.x

### ISSUE THREAD

**Issue by kisuka** [pmatseykanets/laravel-scout-postgres#38]
Scout 7.x is technically available in Laravel 7.x. Can the Scout requirements for the 7.0.0 tag include Scout 7.x and 8.x? I have a setup atm that has v7.2.1 of Lumen and 7.2.1 of Scout. But I can't install the 7.0.0 tag of this package due to it requiring Scout 8.0

**Comment by pmatseykanets** [comment]
#41 Currently in the master. Will tag it soon.
