### ISSUE TITLE
Breaking HTTP Tests

### ISSUE THREAD

**Issue by LouisHrg** [pmatseykanets/laravel-scout-postgres#40]
Hi, 
It appears that when I run my HTTP Tests on my project, the package is breaking the test 

```SQLSTATE[HY000]: General error: 1 near "USING": syntax error (SQL: CREATE INDEX posts_searchable_index ON posts USING GIN (searchable))"```

I followed the doc and it works very well but in my HTTP test :shrug: 
Maybe someone has stumble on the same issue

**Comment by pmatseykanets** [comment]
Hi,

Are you sure you're running your tests against a PosgreSQL instance?

**Comment by LouisHrg** [comment]
Yeap

**Comment by pmatseykanets** [comment]
Well, the error message says otherwise, given that it complains about `USING` keyword. It seems like you're using either MySQL or SQLite in tests.

**Comment by LouisHrg** [comment]
Oh yeah you're right ! :confused: thank you :smile:
